name: Upload APK from URL

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'رابط الـ APK'
        default: 'https://dl.mcpelife.com/minecraft-pe/1-26-23-1/minecraft-1.26.23.1-arm64-v8a.apk'
        required: true
      tag_name:
        description: 'اسم الـ Tag'
        default: 'iqmod_26_23'
        required: true
      release_name:
        description: 'اسم الإصدار'
        default: 'iqmod_26_23'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK
        run: |
          wget -O app.apk "${{ github.event.inputs.apk_url }}"

      - name: Create Release & Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          files: app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
