name: Upload APK from URL

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'رابط الـ APK'
        default: 'https://dl.mcpelife.com/minecraft-pe/1-26-23-1/minecraft-1.26.23.1-arm64-v8a.apk'
        required: true
      file_name:
        description: 'اسم الملف'
        default: 'IQMOD_26_23.apk'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK
        run: |
          wget --no-check-certificate -O "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.apk_url }}"
          ls -lh "${{ github.event.inputs.file_name }}"

      - name: Upload to existing Release
        run: |
          gh release upload "iqmox" "${{ github.event.inputs.file_name }}" \
            --repo "${{ github.repository }}" \
            --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
