name: Upload APK from URL

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'رابط الـ APK'
        default: 'https://dl.mcpelife.com/minecraft-pe/1-26-23-1/minecraft-1.26.23.1-arm64-v8a.apk'
        required: true
      tag_name:
        description: 'اسم الـ Tag'
        default: 'iqmod_26_23'
        required: true
      release_name:
        description: 'اسم الإصدار'
        default: 'iqmod_26_23'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK
        run: |
          wget --no-check-certificate -O app.apk "${{ github.event.inputs.apk_url }}"
          ls -lh app.apk

      - name: Delete old release if exists
        run: |
          gh release delete "${{ github.event.inputs.tag_name }}" --yes --repo "${{ github.repository }}" || true
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release & Upload APK
        run: |
          gh release create "${{ github.event.inputs.tag_name }}" \
            app.apk \
            --title "${{ github.event.inputs.release_name }}" \
            --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
